### ISSUE TITLE
We do not need to have explicit resolvers for most of our properties

### ISSUE THREAD

**Issue by ColeWalker** [ColeWalker/twitch-graphql#132]
Unless we rename a property, graphql can do a lot of the work involved for us.

**Comment by ColeWalker** [comment]
Example can be found in [the redemption pubsub module.](https://github.com/ColeWalker/twitch-graphql/blob/master/src/schema/redemption-pubsub-type-schema.ts)

I also have a [digital garden post on this subject.](https://www.walkermakes.com/digital-garden/notes-on-graphql-resolvers/)

**Comment by ColeWalker** [comment]
https://spin.atomicobject.com/2018/07/25/apollo-default-resolver/

https://github.com/ColeWalker/twitch-graphql/blob/master/src/schema/game-type-schema.ts

In game-type-schema, we don't need any of the game-type resolvers.

**Comment by CodeItQuick** [comment]
Cole - These tests hit the twitch API. My wallaby.js continually runs the tests, I'm going to be hitting the API a ton. I really think you should mock out the reply for each endpoint and use that, or do something similar....

**Comment by ColeWalker** [comment]
Ah I see, I will have to add an issue for that.
