### ISSUE TITLE
Add "Send Chat Message" Mutation

### ISSUE THREAD

**Issue by ColeWalker** [ColeWalker/twitch-graphql#155]
Should accept a channel where chat message is to be sent and the message to be sent to the channel. 

This cannot be part of the chat subscription type as it is not necessarily related to websockets.

Will need to create mutation type in the root schema.

Function should connect to the chat, send the message, then disconnect from the chat.

**Comment by yighax** [comment]
hi, i need to choose git issue for my asignment in school, can i solve this one? i will try be quick as possible, but i am not pro dev, thanks

**Comment by ColeWalker** [comment]
On second thought, just create a userData schema type and add that to the resolvers
